// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMfU_y7JoiMYMJ_4TbrOCTOnHEEJJZr2E',
    appId: '1:268643218431:web:2d97a049a38b490b8e2dca',
    messagingSenderId: '268643218431',
    projectId: 'lunchbox-gen',
    authDomain: 'lunchbox-gen.firebaseapp.com',
    storageBucket: 'lunchbox-gen.firebasestorage.app',
    measurementId: 'G-999G4ED98B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHuV5a5yfyz16bduBJNBD4ho_wSMMzlXU',
    appId: '1:268643218431:android:0621fa6ccd2369668e2dca',
    messagingSenderId: '268643218431',
    projectId: 'lunchbox-gen',
    storageBucket: 'lunchbox-gen.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPp97rYBjxVBpnv1vOoB5mvX0iql9seis',
    appId: '1:268643218431:ios:8aca889c122b31358e2dca',
    messagingSenderId: '268643218431',
    projectId: 'lunchbox-gen',
    storageBucket: 'lunchbox-gen.firebasestorage.app',
    iosBundleId: 'com.aztech.lunchbox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPp97rYBjxVBpnv1vOoB5mvX0iql9seis',
    appId: '1:268643218431:ios:8aca889c122b31358e2dca',
    messagingSenderId: '268643218431',
    projectId: 'lunchbox-gen',
    storageBucket: 'lunchbox-gen.firebasestorage.app',
    iosBundleId: 'com.aztech.lunchbox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMfU_y7JoiMYMJ_4TbrOCTOnHEEJJZr2E',
    appId: '1:268643218431:web:e3eab87a57e4dd5a8e2dca',
    messagingSenderId: '268643218431',
    projectId: 'lunchbox-gen',
    authDomain: 'lunchbox-gen.firebaseapp.com',
    storageBucket: 'lunchbox-gen.firebasestorage.app',
    measurementId: 'G-ZTV2TNSQ65',
  );
}
